version: '3.8'

services:
  symfony-tuduu-web:
    build:
      context: ./
      dockerfile: docker/symfony/Dockerfile
    image: ortegasixto7/symfony-tuduu-web:latest
    container_name: symfony-tuduu-web
    restart: on-failure
    environment:
      APP_ENV: prod
      APP_SECRET: APP_SECRET
      DATABASE_URL: DATABASE_URL
    networks:
      - symfony-tuduu-web-network

  symfony-tuduu-web-nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    image: ortegasixto7/symfony-tuduu-web-nginx:latest
    container_name: symfony-tuduu-web-nginx
    restart: on-failure
    ports:
      - 5000:80
    depends_on:
      - symfony-tuduu-web
    networks:
      - symfony-tuduu-web-network

networks:
  symfony-tuduu-web-network:
    driver: bridge
